### PR TITLE
update Readme with submodule command

### PR DESCRIPTION
**Pull request by nopeppermint**
I had to write the two submodule commands to download the mavlink submodule.

### CODE REVIEW

**Comment by aerialhedgehog** [comment]
thanks @nopeppermint! looks good

**Comment by nopeppermint** [comment]
@aerialhedgehog could you update the mavlink submodule to the latest mavlink https://github.com/mavlink/mavlink/commit/df1bcab88facfc0f319c311582b3f636ec9c6b48 ?

**Comment by nopeppermint** [comment]
submodule updated to https://github.com/mavlink/c_library/commit/7769ef55a9133cd0477f06355e911a9ddee42ff0

**Comment by nopeppermint** [comment]
couldn't the submodule be added to https://github.com/mavlink/mavlink/tree/master/scripts
with another script

**Comment by nopeppermint** [comment]
=> I just created a script for the submodule update
https://github.com/mavlink/mavlink/pull/390

**Comment by aerialhedgehog** [comment]
hey @nopeppermint, apologies, just wrapping up my defense and dissertation.
these changes look fine to me.  @LorenzMeier can we merge this?

**Pull request closed without merging**
